/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AppRouteImport } from './routes/App'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorMedicosRouteImport } from './routes/doctor/medicos'
import { Route as DoctorLogsRouteImport } from './routes/doctor/logs'
import { Route as DoctorDashboardRouteImport } from './routes/doctor/dashboard'
import { Route as DoctorConsultasRouteImport } from './routes/doctor/consultas'
import { Route as DoctorConsultaRouteImport } from './routes/doctor/consulta'
import { Route as DoctorConfiguracionRouteImport } from './routes/doctor/configuracion'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminMedicosRouteImport } from './routes/admin/medicos'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/App',
  path: '/App',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMedicosRoute = DoctorMedicosRouteImport.update({
  id: '/doctor/medicos',
  path: '/doctor/medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorLogsRoute = DoctorLogsRouteImport.update({
  id: '/doctor/logs',
  path: '/doctor/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor/dashboard',
  path: '/doctor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultasRoute = DoctorConsultasRouteImport.update({
  id: '/doctor/consultas',
  path: '/doctor/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultaRoute = DoctorConsultaRouteImport.update({
  id: '/doctor/consulta',
  path: '/doctor/consulta',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConfiguracionRoute = DoctorConfiguracionRouteImport.update({
  id: '/doctor/configuracion',
  path: '/doctor/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMedicosRoute = AdminMedicosRouteImport.update({
  id: '/admin/medicos',
  path: '/admin/medicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/admin/configuracion',
  path: '/admin/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/support': typeof SupportRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/medicos': typeof AdminMedicosRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctor/configuracion': typeof DoctorConfiguracionRoute
  '/doctor/consulta': typeof DoctorConsultaRoute
  '/doctor/consultas': typeof DoctorConsultasRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/logs': typeof DoctorLogsRoute
  '/doctor/medicos': typeof DoctorMedicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/support': typeof SupportRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/medicos': typeof AdminMedicosRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctor/configuracion': typeof DoctorConfiguracionRoute
  '/doctor/consulta': typeof DoctorConsultaRoute
  '/doctor/consultas': typeof DoctorConsultasRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/logs': typeof DoctorLogsRoute
  '/doctor/medicos': typeof DoctorMedicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/App': typeof AppRoute
  '/support': typeof SupportRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/medicos': typeof AdminMedicosRoute
  '/auth/login': typeof AuthLoginRoute
  '/doctor/configuracion': typeof DoctorConfiguracionRoute
  '/doctor/consulta': typeof DoctorConsultaRoute
  '/doctor/consultas': typeof DoctorConsultasRoute
  '/doctor/dashboard': typeof DoctorDashboardRoute
  '/doctor/logs': typeof DoctorLogsRoute
  '/doctor/medicos': typeof DoctorMedicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/App'
    | '/support'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/medicos'
    | '/auth/login'
    | '/doctor/configuracion'
    | '/doctor/consulta'
    | '/doctor/consultas'
    | '/doctor/dashboard'
    | '/doctor/logs'
    | '/doctor/medicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/App'
    | '/support'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/medicos'
    | '/auth/login'
    | '/doctor/configuracion'
    | '/doctor/consulta'
    | '/doctor/consultas'
    | '/doctor/dashboard'
    | '/doctor/logs'
    | '/doctor/medicos'
  id:
    | '__root__'
    | '/'
    | '/App'
    | '/support'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/medicos'
    | '/auth/login'
    | '/doctor/configuracion'
    | '/doctor/consulta'
    | '/doctor/consultas'
    | '/doctor/dashboard'
    | '/doctor/logs'
    | '/doctor/medicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  SupportRoute: typeof SupportRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMedicosRoute: typeof AdminMedicosRoute
  AuthLoginRoute: typeof AuthLoginRoute
  DoctorConfiguracionRoute: typeof DoctorConfiguracionRoute
  DoctorConsultaRoute: typeof DoctorConsultaRoute
  DoctorConsultasRoute: typeof DoctorConsultasRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorLogsRoute: typeof DoctorLogsRoute
  DoctorMedicosRoute: typeof DoctorMedicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/App': {
      id: '/App'
      path: '/App'
      fullPath: '/App'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/medicos': {
      id: '/doctor/medicos'
      path: '/doctor/medicos'
      fullPath: '/doctor/medicos'
      preLoaderRoute: typeof DoctorMedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/logs': {
      id: '/doctor/logs'
      path: '/doctor/logs'
      fullPath: '/doctor/logs'
      preLoaderRoute: typeof DoctorLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard': {
      id: '/doctor/dashboard'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consultas': {
      id: '/doctor/consultas'
      path: '/doctor/consultas'
      fullPath: '/doctor/consultas'
      preLoaderRoute: typeof DoctorConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consulta': {
      id: '/doctor/consulta'
      path: '/doctor/consulta'
      fullPath: '/doctor/consulta'
      preLoaderRoute: typeof DoctorConsultaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/configuracion': {
      id: '/doctor/configuracion'
      path: '/doctor/configuracion'
      fullPath: '/doctor/configuracion'
      preLoaderRoute: typeof DoctorConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/medicos': {
      id: '/admin/medicos'
      path: '/admin/medicos'
      fullPath: '/admin/medicos'
      preLoaderRoute: typeof AdminMedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  SupportRoute: SupportRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMedicosRoute: AdminMedicosRoute,
  AuthLoginRoute: AuthLoginRoute,
  DoctorConfiguracionRoute: DoctorConfiguracionRoute,
  DoctorConsultaRoute: DoctorConsultaRoute,
  DoctorConsultasRoute: DoctorConsultasRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorLogsRoute: DoctorLogsRoute,
  DoctorMedicosRoute: DoctorMedicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
