/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DoctorMedicosIndexRouteImport } from './routes/doctor/medicos/index'
import { Route as DoctorHistorialIndexRouteImport } from './routes/doctor/historial/index'
import { Route as DoctorDashboardIndexRouteImport } from './routes/doctor/dashboard/index'
import { Route as DoctorConsultaIndexRouteImport } from './routes/doctor/consulta/index'
import { Route as DoctorConfiguracionIndexRouteImport } from './routes/doctor/configuracion/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AdminMedicosIndexRouteImport } from './routes/admin/medicos/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin/dashboard/index'
import { Route as AdminConfiguracionIndexRouteImport } from './routes/admin/configuracion/index'
import { Route as AdminLogsIndexRouteImport } from './routes/admin/Logs/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorMedicosIndexRoute = DoctorMedicosIndexRouteImport.update({
  id: '/doctor/medicos/',
  path: '/doctor/medicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorHistorialIndexRoute = DoctorHistorialIndexRouteImport.update({
  id: '/doctor/historial/',
  path: '/doctor/historial/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardIndexRoute = DoctorDashboardIndexRouteImport.update({
  id: '/doctor/dashboard/',
  path: '/doctor/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConsultaIndexRoute = DoctorConsultaIndexRouteImport.update({
  id: '/doctor/consulta/',
  path: '/doctor/consulta/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorConfiguracionIndexRoute =
  DoctorConfiguracionIndexRouteImport.update({
    id: '/doctor/configuracion/',
    path: '/doctor/configuracion/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMedicosIndexRoute = AdminMedicosIndexRouteImport.update({
  id: '/admin/medicos/',
  path: '/admin/medicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin/dashboard/',
  path: '/admin/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracionIndexRoute = AdminConfiguracionIndexRouteImport.update({
  id: '/admin/configuracion/',
  path: '/admin/configuracion/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsIndexRoute = AdminLogsIndexRouteImport.update({
  id: '/admin/Logs/',
  path: '/admin/Logs/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/support': typeof SupportRoute
  '/admin/Logs/': typeof AdminLogsIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/medicos/': typeof AdminMedicosIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/doctor/configuracion/': typeof DoctorConfiguracionIndexRoute
  '/doctor/consulta/': typeof DoctorConsultaIndexRoute
  '/doctor/dashboard/': typeof DoctorDashboardIndexRoute
  '/doctor/historial/': typeof DoctorHistorialIndexRoute
  '/doctor/medicos/': typeof DoctorMedicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/support': typeof SupportRoute
  '/admin/Logs': typeof AdminLogsIndexRoute
  '/admin/configuracion': typeof AdminConfiguracionIndexRoute
  '/admin/dashboard': typeof AdminDashboardIndexRoute
  '/admin/medicos': typeof AdminMedicosIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/doctor/configuracion': typeof DoctorConfiguracionIndexRoute
  '/doctor/consulta': typeof DoctorConsultaIndexRoute
  '/doctor/dashboard': typeof DoctorDashboardIndexRoute
  '/doctor/historial': typeof DoctorHistorialIndexRoute
  '/doctor/medicos': typeof DoctorMedicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/support': typeof SupportRoute
  '/admin/Logs/': typeof AdminLogsIndexRoute
  '/admin/configuracion/': typeof AdminConfiguracionIndexRoute
  '/admin/dashboard/': typeof AdminDashboardIndexRoute
  '/admin/medicos/': typeof AdminMedicosIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/doctor/configuracion/': typeof DoctorConfiguracionIndexRoute
  '/doctor/consulta/': typeof DoctorConsultaIndexRoute
  '/doctor/dashboard/': typeof DoctorDashboardIndexRoute
  '/doctor/historial/': typeof DoctorHistorialIndexRoute
  '/doctor/medicos/': typeof DoctorMedicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/support'
    | '/admin/Logs/'
    | '/admin/configuracion/'
    | '/admin/dashboard/'
    | '/admin/medicos/'
    | '/auth/login/'
    | '/doctor/configuracion/'
    | '/doctor/consulta/'
    | '/doctor/dashboard/'
    | '/doctor/historial/'
    | '/doctor/medicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/support'
    | '/admin/Logs'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/medicos'
    | '/auth/login'
    | '/doctor/configuracion'
    | '/doctor/consulta'
    | '/doctor/dashboard'
    | '/doctor/historial'
    | '/doctor/medicos'
  id:
    | '__root__'
    | '/'
    | '/support'
    | '/admin/Logs/'
    | '/admin/configuracion/'
    | '/admin/dashboard/'
    | '/admin/medicos/'
    | '/auth/login/'
    | '/doctor/configuracion/'
    | '/doctor/consulta/'
    | '/doctor/dashboard/'
    | '/doctor/historial/'
    | '/doctor/medicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupportRoute: typeof SupportRoute
  AdminLogsIndexRoute: typeof AdminLogsIndexRoute
  AdminConfiguracionIndexRoute: typeof AdminConfiguracionIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminMedicosIndexRoute: typeof AdminMedicosIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  DoctorConfiguracionIndexRoute: typeof DoctorConfiguracionIndexRoute
  DoctorConsultaIndexRoute: typeof DoctorConsultaIndexRoute
  DoctorDashboardIndexRoute: typeof DoctorDashboardIndexRoute
  DoctorHistorialIndexRoute: typeof DoctorHistorialIndexRoute
  DoctorMedicosIndexRoute: typeof DoctorMedicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/medicos/': {
      id: '/doctor/medicos/'
      path: '/doctor/medicos'
      fullPath: '/doctor/medicos/'
      preLoaderRoute: typeof DoctorMedicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/historial/': {
      id: '/doctor/historial/'
      path: '/doctor/historial'
      fullPath: '/doctor/historial/'
      preLoaderRoute: typeof DoctorHistorialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/dashboard/': {
      id: '/doctor/dashboard/'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard/'
      preLoaderRoute: typeof DoctorDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/consulta/': {
      id: '/doctor/consulta/'
      path: '/doctor/consulta'
      fullPath: '/doctor/consulta/'
      preLoaderRoute: typeof DoctorConsultaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/configuracion/': {
      id: '/doctor/configuracion/'
      path: '/doctor/configuracion'
      fullPath: '/doctor/configuracion/'
      preLoaderRoute: typeof DoctorConfiguracionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/medicos/': {
      id: '/admin/medicos/'
      path: '/admin/medicos'
      fullPath: '/admin/medicos/'
      preLoaderRoute: typeof AdminMedicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard/': {
      id: '/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracion/': {
      id: '/admin/configuracion/'
      path: '/admin/configuracion'
      fullPath: '/admin/configuracion/'
      preLoaderRoute: typeof AdminConfiguracionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/Logs/': {
      id: '/admin/Logs/'
      path: '/admin/Logs'
      fullPath: '/admin/Logs/'
      preLoaderRoute: typeof AdminLogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupportRoute: SupportRoute,
  AdminLogsIndexRoute: AdminLogsIndexRoute,
  AdminConfiguracionIndexRoute: AdminConfiguracionIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminMedicosIndexRoute: AdminMedicosIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  DoctorConfiguracionIndexRoute: DoctorConfiguracionIndexRoute,
  DoctorConsultaIndexRoute: DoctorConsultaIndexRoute,
  DoctorDashboardIndexRoute: DoctorDashboardIndexRoute,
  DoctorHistorialIndexRoute: DoctorHistorialIndexRoute,
  DoctorMedicosIndexRoute: DoctorMedicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
